### ISSUE TITLE
Panic with completely black image

### ISSUE THREAD

**Issue by Pe46dro** [EdlinOrg/prominentcolor#2]
Hi,
 I'm found a problem while i try to check dominant color on completely black image like the one below.
 
![black](https://user-images.githubusercontent.com/6197075/35195588-109e4fee-fec6-11e7-82c5-4a2274fa04a9.jpg)

This is my code:
```go
cols := prominentcolor.KmeansWithAll(3, img, prominentcolor.ArgumentNoCropping, 80, []prominentcolor.ColorBackgroundMask{})

col := cols[0].AsString()
fmt.Println("#"+col)
```

This is the output that i recive:
```log
2018/01/21 16:31:05 Failed, k larger than len(allColors): 3 vs 0
panic: invalid argument to Intn

goroutine 1 [running]:
math/rand.(*Rand).Intn(0xc042072270, 0x0, 0x3)
	{GO_PATH}/src/math/rand/rand.go:142 +0xa3
math/rand.Intn(0x0, 0x0)
	{GO_PATH}/src/math/rand/rand.go:277 +0x3e
github.com/EdlinOrg/prominentcolor.kmeansPlusPlusSeed(0x3, 0x8, 0x614528, 0x0, 0x0, 0x0, 0x0, 0x0)
	{GO_PATH}/src/github.com/EdlinOrg/prominentcolor/kmeans.go:387 +0xd7
github.com/EdlinOrg/prominentcolor.kmeansSeed(0x3, 0x614528, 0x0, 0x0, 0x8, 0x0, 0xc0429de3c0, 0x5e3700)
	{GO_PATH}/src/github.com/EdlinOrg/prominentcolor/kmeans.go:357 +0x18e
github.com/EdlinOrg/prominentcolor.KmeansWithAll(0x3, 0x5e3700, 0xc0429de3c0, 0x8, 0x50, 0xc04296dec4, 0x3, 0x3, 0x501daa, 0xc042002020, ...)
	{GO_PATH}/src/github.com/EdlinOrg/prominentcolor/kmeans.go:111 +0x104
github.com/EdlinOrg/prominentcolor.KmeansWithArgs(0x8, 0x5e3700, 0xc0429de3c0, 0xc0429de3c0, 0x0, 0x0)
	{GO_PATH}/src/github.com/EdlinOrg/prominentcolor/kmeans.go:101 +0x104
main.main()
	{PROJECT_PATH}/main.go:38 +0x1d1
```

At the moment i moved to jakekausler/prominentcolor@7583347b935415ac0b34343888fc2b35c6f2e1e7 a fork of this project that return errors instead of panic, so i can handle exceptions.

How can i have `#000000` instead of panic?

**Comment by EdlinOrg** [comment]
Nice, I pulled in those changes here. Odd that it finds 0 colors. The way you call it is correct to get it to ignore the masks, I tried with the image above and your call, and it found 1 color. I submitted some minor (unrelated) fixes, so please pull and try again. If you still have issues, can you please mail me the image you use, and I'll try again.
