### ISSUE TITLE
v1.0

### ISSUE THREAD

**Issue by wayneashleyberry** [EdlinOrg/prominentcolor#5]
It would be great to get a v1 tagged release on this project :)

**Comment by EdlinOrg** [comment]
sure, why not, there you go: https://github.com/EdlinOrg/prominentcolor/releases

**Comment by wayneashleyberry** [comment]
Fantastic! Thank you @EdlinOrg

**Comment by wayneashleyberry** [comment]
@EdlinOrg unfortunately the tag you added isn't semver compliant, so go modules aren't picking it up... would you mind adding a v1.0.0 (or even v1.0.1 now?)

**Comment by EdlinOrg** [comment]
@wayneashleyberry better now?

**Comment by wayneashleyberry** [comment]
Yeah, perfect - thanks!
